version: '3'
services:
  db:
    image: mysql:8.0
    container_name: 'GM2-DB'
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    tty: true
    restart: always

  api:
    build: ./api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec pumactl start"
    container_name: 'GM2-API'
    volumes:
      - ./api:/myapp
      - /etc/letsencrypt:/certs:ro
    ports:
      - "3000:9292" #local:pumactl
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment: 
      - RAILS_ENV=production
    
  view:
    build: ./view
    container_name: 'GM2-VIEW'
    ports: 
      - "8080:8080"
    volumes:
      - ./view:/app
      - code_share:/app/vue-project/dist
    stdin_open: true
    tty: true
    environment:
      - VUE_APP_URL=https://group-manager-api.nutfes.net
    depends_on:
      - api

  admin_view:
    build: ./admin_view
    container_name: 'GM2-ADMIN-VIEW'
    ports:
      - "8000:8000"
    command: npm run start
    volumes:
      - ./admin_view:/app
    tty: true
    environment:
      - VUE_APP_URL=https://group-manager-api.nutfes.net


  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - code_share:/var/www/vhosts/group-manager.nutfes.net
    ports:
      - 10001:80
    depends_on:
      - admin_view
      - api

volumes:
  mysql-data:
    driver: local
  code_share: 
