version: "3"
services:
  api:
    build: ./api
    command: bash -c "bundle exec rails s"
    container_name: "GM2-API"
    volumes:
      - ./api:/myapp
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=ON
    env_file:
      - nutmeg-mysql.env
      - webhook.env

  view: #  build only
    build: ./view
    container_name: "GM2-VIEW"
    volumes:
      - ./view:/app
    environment:
      - VUE_APP_URL=https://group-manager-api.nutfes.net

  admin_view:
    build: ./admin_view
    container_name: "GM2-ADMIN-VIEW"
    ports:
      - "8000:8000"
    command: sh -c "npm run start"
    volumes:
      - ./admin_view:/app
    tty: true
    environment:
      - VUE_APP_URL=https://group-manager-api.nutfes.net

  web:
    image: nginx:1.17
    container_name: "GM2-WEB"
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./inside_view/vue-project/dist:/var/www/vhosts/group-manager-inside.nutfes.net
      - ./view/vue-project/dist:/var/www/vhosts/group-manager.nutfes.net
    ports:
      - "8080:8080"
      - "8888:8888"
    depends_on:
      - admin_view
      - api

  cloudflare:
    image: cloudflare/cloudflared
    container_name: "GM2-CLOUDFLARE"
    volumes:
      - ./cloudflare/stage:/home/nonroot/.cloudflared
    command: tunnel run

volumes:
  mysql-data:
    driver: local
  code_share:
