version: "3"
services:
  db:
    image: mysql:8.0
    container_name: "GM2-DB"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_USER: root
      MYSQL_USER: group-manager-2
      MYSQL_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
    ports: ["3306:3306"]
    volumes: [mysql-data:/var/lib/mysql]

  cloudflare:
    image: cloudflare/cloudflared
    container_name: "GM2-CLOUDFLARE"
    volumes: [./cloudflare/stage:/home/nonroot/.cloudflared]
    command: tunnel run

  api:
    build: ./api
    command: bash -c "bundle exec rails s"
    container_name: "GM2-API"
    volumes: [./api:/myapp]
    ports: ["3000:3000"]
    env_file: [group-manager-2.stg.env]

  user_front:
    build: ./user_front
    container_name: "GM2-USER-FRONT"
    ports:
      - "8002:3000"
      - "24678:24678"
    command: bash -c "npm run start"
    volumes: [./user_front:/app]
    env_file: [group-manager-2.stg.env]
    depends_on: [api]

  admin_view:
    build: ./admin_view
    container_name: "GM2-ADMIN-VIEW"
    ports: ["8000:8000"]
    command: bash -c "npm run start"
    volumes: [./admin_view:/app]
    env_file: [group-manager-2.stg.env]

volumes:
  mysql-data:
    driver: local
