version: '3'
services:
  db:
    image: mysql:8.0
    container_name: 'GM2-DB'
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    tty: true

  api:
    build: ./api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: 'GM2-API'
    volumes:
      - ./api:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    networks: 
      - proxy
    
  view:
    build: ./view
    command: npm run serve
    container_name: 'GM2-VIEW'
    ports:
      - "8080:8080"
    volumes:
      - ./view:/app
    stdin_open: true
    tty: true
    environment:
      - VUE_APP_URL=http://localhost:3000
    networks: 
      - proxy

  admin_view:
    build: ./admin_view
    container_name: 'GM2-ADMIN-VIEW'
    ports:
      - "8000:8000"
    command: npm run dev
    volumes:
      - ./admin_view:/app
    tty: true
    environment:
      - VUE_APP_URL=http://localhost:3000
    networks: 
      - proxy

  nginx:
    container_name: 'nginx'
    ports:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - api
      - view
      - admin_view
    networks: 
      - proxy

volumes:
  mysql-data:
    driver: local

networks:
  proxy:
    external: true
