version: '3'
services:
  api:
    build: ./api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec pumactl start"
    container_name: 'GM2-API'
    volumes:
      - ./api:/myapp
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment: 
      - RAILS_ENV=production
    env_file:
      - nutmeg-mysql.env

  view: #  build only
    build: ./view
    container_name: 'GM2-VIEW'
    volumes:
      - ./view:/app
    environment:
      - VUE_APP_URL=https://group-manager-api.nutfes.net

  inside_view: #  build only
    build: ./inside_view
    container_name: 'GM2-INSIDE-VIEW'
    volumes:
      - ./inside_view:/app
    environment:
      - VUE_APP_URL=https://group-manager-api.nutfes.net

  admin_view:
    build: ./admin_view
    container_name: 'GM2-ADMIN-VIEW'
    ports:
      - "8000:8000"
    command: npm run start
    volumes:
      - ./admin_view:/app
    tty: true
    environment:
      - VUE_APP_URL=https://group-manager-api.nutfes.net

  web:
    image: nginx:1.17
    container_name: 'GM2-WEB'
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./inside_view/vue-project/dist:/var/www/vhosts/group-manager-inside.nutfes.net
      - ./view/vue-project/dist:/var/www/vhosts/group-manager.nutfes.net
    ports:
      - 80:80
    depends_on:
      - admin_view
      - api

volumes:
  mysql-data:
    driver: local
  code_share: 
