version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql

  api:
    build: ./api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/myapp
    ports:
      - "80:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    
  view:
    build: ./view
    command: npm run serve
    ports:
      - "8080:8080"
    volumes:
      - ./view:/app
    stdin_open: true
    tty: true
    environment:
      - VUE_APP_URL=http://localhost

  # admin_view:
  #   build: ./admin_view
  #   command: npm run dev
  #   ports:
  #     - "8081:8081"
  #   volumes:
  #     - ./admin_view:/app
  #   stdin_open: true
  #   tty: true
  #   environment:
  #     - VUE_APP_URL=0.0.0.0

volumes:
  mysql-data:
    driver: local
