version: '3'
services:
  production_db:
    image: mysql:8.0
    container_name: 'GM2-PROD-DB'
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    tty: true
    stdin_open: true

  api:
    build: ./api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -e production"
    container_name: 'GM2-API'
    volumes:
      - ./api:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - production_db
    stdin_open: true
    tty: true
    
  view:
    build: ./view
    container_name: 'GM2-VIEW'
    ports:
      - "8080:8080"
    volumes:
      - ./view:/app
      - code_share:/app/vue-project/dist
    stdin_open: true
    tty: true
    environment:
      - VUE_APP_URL=http://localhost:3000
    depends_on:
      - api

  admin_view:
    build: ./admin_view
    container_name: 'GM2-ADMIN-VIEW'
    ports:
      - "8000:8000"
    command: npm run start
    volumes:
      - ./admin_view:/app
    tty: true
    environment:
      - VUE_APP_URL=http://133.125.44.106:3000

  nginx:
    container_name: 'nginx'
    build: ./nginx
    volumes:
      - code_share:/var/www/public
    ports:
      - 80:80
    depends_on:
      - api
      - view
      - admin_view

volumes:
  mysql-data:
    driver: local
  code_share: 
