version: "3"
services:
  cloudflare:
    image: cloudflare/cloudflared
    container_name: "GM2-CLOUDFLARE"
    volumes:
      - ./cloudflare/prod:/home/nonroot/.cloudflared
    command: tunnel run

  api:
    build: ./api
    command: bash -c "bundle exec rails s"
    container_name: "GM2-API"
    volumes: [./api:/myapp]
    ports: ["3000:3000"]
    env_file: [group-manager-2.env]

  user_front:
    build: ./user_front
    container_name: "GM2-USER-FRONT"
    ports:
      - "8002:8002"
      - "24678:24678"
    command: npm run start
    volumes: [./user_front:/app]
    env_file: [group-manager-2.env]
    depends_on: [api]

  admin_view:
    build: ./admin_view
    container_name: "GM2-ADMIN-VIEW"
    ports: ["8000:8000"]
    command: npm run start
    volumes: [./admin_view:/app]
    env_file: [group-manager-2.env]
