version: "3"
services:
  cloudflare:
    image: cloudflare/cloudflared
    container_name: "GM2-CLOUDFLARE"
    volumes:
      - ./cloudflare/prod:/home/nonroot/.cloudflared
    command: tunnel run

  api:
    build: ./api
    command: bash -c "bundle exec rails s"
    container_name: "GM2-API"
    volumes: [./api:/myapp]
    env_file: [group-manager-2.env]

  user_front:
    build: ./user_front
    container_name: "GM2-USER-FRONT"
    command: bash -c "npm run start"
    volumes: [./user_front:/app]
    env_file: [group-manager-2.env]
    depends_on: [api]

  admin_view:
    build: ./admin_view
    container_name: "GM2-ADMIN-VIEW"
    command: bash -c "npm run start"
    volumes: [./admin_view:/app]
    env_file: [group-manager-2.env]
