tunnel: 7c8b780f-8330-4419-b24c-8f81f825528d
credentials-file: /home/nonroot/.cloudflared/7c8b780f-8330-4419-b24c-8f81f825528d.json
protocol: http2

ingress:
  - hostname: group-manager.stg.nutfes.net
    service: http://web:8080
  - hostname: group-manager-admin.stg.nutfes.net
    service: http://admin_view:8000
  - hostname: group-manager-api.stg.nutfes.net
    service: http://api:3000
  - service: http_status:404
