export const inventoryManagementRole = {
    employees: {
        read:   false,
        create: false,
        update: false,
        delete: false,
      },
      fes_dates: {
        read:   false,
        create: false,
        update: false,
        delete: false,
      },
      fes_years: {
        read:   false,
        create: false,
        update: false,
        delete: false,
      },
      food_products: {
        read:   false,
        create: false,
        update: false,
        delete: false,
      },
      groups: {
        read:   false,
        create: false,
        update: false,
        delete: false,
      },
      news: {
        read:   false,
        create: false,
        update: false,
        delete: false,
      },
      place_allow_lists: {
        read:   false,
        create: false,
        update: false,
        delete: false,
      },
      place_orders: {
        read:   false,
        create: false,
        update: false,
        delete: false,
      },
      places: {
        read:   false,
        create: false,
        update: false,
        delete: false,
      },
      power_orders: {
        read:   false,
        create: false,
        update: false,
        delete: false,
      },
      print: {
        read:   false,
        create: false,
        update: false,
        delete: false,
      },
      project_names: {
        read:   false,
        create: false,
        update: false,
        delete: false,
      },
      public_relations: {
        read:   false,
        create: false,
        update: false,
        delete: false,
      },
      purchase_lists: {
        read:   false,
        create: false,
        update: false,
        delete: false,
      },
      rentable_items: {
        read:   false,
        create: false,
        update: false,
        delete: false,
      },
      rental_item_allow_lists: {
        read:   true,
        create: true,
        update: true,
        delete: true,
      },
      rental_items: {
        read:   true,
        create: true,
        update: true,
        delete: true,
      },
      rental_orders: {
        read:   true,
        create: true,
        update: true,
        delete: true,
      },
      representatives: {
        read:   false,
        create: false,
        update: false,
        delete: false,
      },
      shops: {
        read:   false,
        create: false,
        update: false,
        delete: false,
      },
      stage_common_options: {
        read:   false,
        create: false,
        update: false,
        delete: false,
      },
      stage_orders: {
        read:   false,
        create: false,
        update: false,
        delete: false,
      },
      stages: {
        read:   false,
        create: false,
        update: false,
        delete: false,
      },
      stocker_items: {
        read:   true,
        create: true,
        update: true,
        delete: true,
      },
      stocker_places: {
        read:   true,
        create: true,
        update: true,
        delete: true,
      },
      user_page_setting: {
        read:   false,
        create: false,
        update: false,
        delete: false,
      },
      users: {
        read:   false,
        create: false,
        update: false,
        delete: false,
      },
      assgin_items: {
        read:   true,
        create: true,
        update: true,
        delete: true,
      },
      announcements: {
        read:   false,
        create: false,
        update: false,
        delete: false,
      },
      group_identify: {
        read: false,
        create: false,
        update: false,
        delete: false,
      },
      order_status: {
        read:   true,
        create: true,
        update: true,
        delete: true,
      },
      venue_maps:{
        read: true,
        create: false,
        update: false,
        delete: false,
      },
  };
