name: "Chromatic"

on:
    pull_request:
      paths:
        - "user/**"
        - ".github/workflows/chromatic.yml"

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ./user
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # pnpm を明示的にセットアップしてから setup-node の cache を使う
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
            version: 10.7.0
      # Node.js v22をセットアップ
      - name: Use Node.js v22
        uses: actions/setup-node@v4
        with:
            node-version: '22'
            cache: 'pnpm'
            cache-dependency-path: ./user/pnpm-lock.yaml
      # pnpmで依存関係をインストール
      - name: pnpm install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./user
      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: ./user
