name: "Chromatic"

on:
    pull_request:
        paths:
          - "user/**"
          - ".github/workflows/chromatic.yml"

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ./user
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
      - name: Install dependencies
        working-directory: ./user
        run: pnpm i
      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: ./user
