name: Lint
on: 
  push:
    paths:
      - '**.vue'
      - '**.js'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node.js 16.12.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.12.0
      - name: ESLint
        run: npm run lint
