name: CI

on:
  push:
    branches:
      - main
      - feat/mitomen/2031/CI-CD-pipeline
  workflow_call:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v6
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT || github.token }}

      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
          tags: tag:ci

      - name: Configure Insecure Registry
        run: |
          sudo service docker stop
          echo "{\"insecure-registries\": [\"${{ secrets.HARBOR_REG }}\"]}" | sudo tee /etc/docker/daemon.json
          sudo service docker start

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
          buildkitd-config-inline: |
            [registry."${{ secrets.HARBOR_REG }}"]
              http = true
              insecure = true

      - name: Log in to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_REG }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASS }}

      - name: Build and Push API
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: ${{ secrets.HARBOR_REG }}/group-manager/api:latest
          cache-from: type=gha

      - name: Build and Push User
        uses: docker/build-push-action@v5
        with:
          context: ./user
          file: ./user/prod.Dockerfile
          push: true
          tags: ${{ secrets.HARBOR_REG }}/group-manager/user:latest
          cache-from: type=gha
          build-args: |
            NODE_ENV=${{ secrets.NODE_ENV }}
            APP_ENV=${{ secrets.APP_ENV }}
            NEXT_PUBLIC_IMGUR_CLIENT_ID=${{ secrets.NEXT_PUBLIC_IMGUR_CLIENT_ID }}
            IMGUR_CLIENT_SECRET=${{ secrets.IMGUR_CLIENT_SECRET }}
            NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}

      - name: Build and Push Admin View
        uses: docker/build-push-action@v5
        with:
          context: ./admin_view
          file: ./admin_view/prod.Dockerfile
          push: true
          tags: ${{ secrets.HARBOR_REG }}/group-manager/admin:latest
          cache-from: type=gha
          build-args: |
            VUE_APP_URL=${{ secrets.VUE_APP_URL }}
            VUE_APP_API_URL=${{ secrets.VUE_APP_API_URL }}

  trigger-cd:
    needs: build-and-push
    uses: ./.github/workflows/deployment-prod.yml
    secrets: inherit
